#!/bin/bash

subcommand=$1
shift

version=
app=

while getopts "v:a:" opt; do
  case $opt in
    v ) version=$OPTARG
      ;;
    a ) app=$OPTARG
      ;;
    \? )
        echo "Usage: plantbuild -a=app1 -v=1.0.0"
        exit 1
      ;;
  esac
done

jsonnetfile="$(pwd)/plantbuild/$subcommand.jsonnet"
# echo $jsonnetfile
if ! [ -e $jsonnetfile ]; then
    commands=`ls ./plantbuild/*.jsonnet 2>/dev/null | awk -v FS='/' '{print $3}'| awk -v FS='.' '{print $1}'`
    if [ -z "$commands" ]; then
        echo "please create ./plantbuild and put some jsonnet files there"
        exit 1
    fi
    echo "command '$sub_command' not exist, use these:"
    echo $commands
    exit
fi

if [ -z $app ]; then
    docker run --rm -e RUN=/src/$subcommand.jsonnet -e VERSION=$version -v `pwd`/plantbuild:/src registry.theplant-dev.com/theplant/plantbuild | docker-compose -f - up
else
    docker run --rm -e RUN=/src/$subcommand.jsonnet -e VERSION=$version -v `pwd`/plantbuild:/src registry.theplant-dev.com/theplant/plantbuild | docker-compose -f - run --rm $app
fi
